server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

keys:
  auth: ./keys/jwt_example.key

app:
  token:
    access:
      in:
        minutes: 43200
    refresh:
      in:
        minutes: 10080